version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/samples/aws-sqs"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories: 
      - "/playwright"
      - "/samples/dapr/nodeapp"
      - "/samples/demo"
      - "/samples/demo/client"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories: 
      - "/samples/aws"
      - "/samples/dapr/ui"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/samples/volumes/src"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"